import type { A2UITemplateRegistration, A2UITemplateSlot } from "./template-types";

const now = "2026-07-01T00:00:00.000Z";
const schemaVersion = "2026-06-11" as const;

export const TELEMETRY_STATUS_TEMPLATE_ID = "matrix.table";

function titleSlot(slot = "items[].title"): A2UITemplateSlot {
  return {
    slot,
    acceptsTypes: ["string"],
    acceptsRoles: ["title", "label"],
    required: true,
  };
}

export const INITIAL_TEMPLATES: A2UITemplateRegistration[] = [
  {
    componentId: "collection.list",
    title: "목록",
    description: "제목과 설명이 있는 반복 데이터를 세로 목록으로 보여준다.",
    selectionGuide: "반복 row에 title/name/label과 description/content/summary가 있고 카드, 표, 진행률, 타임라인 신호가 약할 때 사용한다.",
    schemaSpec: {
      dataShape: "array<object>",
      requiredRoles: ["title"],
      optionalRoles: ["content", "description", "category", "status", "updatedAt"],
      fieldHints: {
        title: ["title", "name", "label"],
        content: ["description", "content", "summary"],
        category: ["category", "type"],
        status: ["status", "state"],
        updatedAt: ["updatedAt", "updated_at", "lastUpdatedAt"],
      },
      intentKeywords: ["목록", "리스트", "list", "검색 결과", "문서", "공지"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["array<object>"], minRows: 1 },
      requiredSlots: [titleSlot()],
      optionalSlots: [
        { slot: "items[].description", acceptsTypes: ["string"], acceptsRoles: ["content", "description"], required: false },
        { slot: "items[].category", acceptsTypes: ["string"], acceptsRoles: ["category"], required: false },
        { slot: "items[].status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: false },
        { slot: "items[].updatedAt", acceptsTypes: ["date", "datetime", "string"], acceptsRoles: ["updatedAt", "time"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["목록", "리스트", "list", "검색 결과", "문서", "공지"],
        bestFor: ["generic title and description list"],
        badFor: ["image cards", "status matrix", "progress bars", "timeline"],
        priority: 1,
      },
    },
    surfaceConfig: {
      viewType: "collection.list",
      titleBinding: "items[].title",
      contentBinding: "items[].description",
      categoryBinding: "items[].category",
      statusBindings: ["items[].status"],
      timeBinding: "items[].updatedAt",
      maxItems: 8,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "collection.cardGrid",
    title: "카드 그리드",
    description: "항목을 카드 단위로 배열해 이미지, 설명, 메타 정보를 함께 보여준다.",
    selectionGuide: "이미지/썸네일이 있거나 항목별 설명, 카테고리, 상태를 카드로 스캔하는 것이 적합할 때 사용한다.",
    schemaSpec: {
      dataShape: "array<object>",
      requiredRoles: ["title"],
      optionalRoles: ["image", "content", "description", "category", "status", "metric"],
      fieldHints: {
        title: ["title", "name", "label"],
        image: ["imageUrl", "thumbnailUrl", "photoUrl", "image"],
        content: ["description", "content", "summary"],
        category: ["category", "type"],
      },
      intentKeywords: ["카드", "그리드", "이미지", "사진", "썸네일", "catalog", "card"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["array<object>"], minRows: 1 },
      requiredSlots: [titleSlot("cards[].title")],
      optionalSlots: [
        { slot: "cards[].image", acceptsTypes: ["string"], acceptsRoles: ["image", "uri"], acceptsFormats: ["image-url", "uri"], required: false },
        { slot: "cards[].description", acceptsTypes: ["string"], acceptsRoles: ["content", "description"], required: false },
        { slot: "cards[].category", acceptsTypes: ["string"], acceptsRoles: ["category"], required: false },
        { slot: "cards[].status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["카드", "그리드", "이미지", "사진", "썸네일", "catalog", "card"],
        bestFor: ["visual or metadata rich cards"],
        badFor: ["dense tabular comparison", "large row count"],
        priority: 4,
      },
    },
    surfaceConfig: {
      viewType: "collection.cardGrid",
      titleBinding: "items[].title",
      contentBinding: "items[].description",
      imageBinding: "items[].image",
      categoryBinding: "items[].category",
      statusBindings: ["items[].status"],
      maxItems: 6,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "record.detail",
    title: "상세",
    description: "단일 객체나 하나의 row를 header와 key-value 섹션으로 보여준다.",
    selectionGuide: "응답이 단일 object이거나 row가 하나이고 여러 scalar field를 상세로 읽는 것이 적합할 때 사용한다.",
    schemaSpec: {
      dataShape: "object",
      requiredRoles: ["title"],
      optionalRoles: ["content", "description", "status", "updatedAt", "metric", "category"],
      fieldHints: {
        title: ["title", "name", "label", "displayName"],
        content: ["description", "content", "summary"],
        status: ["status", "state"],
      },
      intentKeywords: ["상세", "detail", "프로필", "요약", "단일", "객체"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["object", "array<object>"], minRows: 1, maxRows: 1 },
      requiredSlots: [titleSlot("record.title")],
      optionalSlots: [
        { slot: "record.description", acceptsTypes: ["string"], acceptsRoles: ["content", "description"], required: false },
        { slot: "record.status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: false },
        { slot: "record.fields", acceptsTypes: ["string", "number", "boolean", "date", "datetime"], acceptsRoles: ["id", "category", "metric", "updatedAt", "time", "status", "label"], minCount: 2, required: false },
      ],
      selectionHints: {
        queryKeywords: ["상세", "detail", "프로필", "단일", "객체"],
        bestFor: ["single record detail"],
        badFor: ["multi-row comparison"],
        priority: 7,
      },
    },
    surfaceConfig: {
      viewType: "record.detail",
      titleBinding: "items[].title",
      contentBinding: "items[].description",
      statusBindings: ["items[].status"],
      fieldBindings: ["items[].id", "items[].category", "items[].updatedAt"],
      maxItems: 1,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "matrix.table",
    title: "데이터 테이블",
    description: "여러 scalar field를 가진 반복 데이터를 행과 열로 보여준다.",
    selectionGuide: "row가 여러 개이고 컬럼 비교가 핵심이며 status/progress/timeline/tree 신호보다 일반 table 표현이 적합할 때 사용한다.",
    schemaSpec: {
      dataShape: "array<object>",
      requiredRoles: ["title"],
      optionalRoles: ["metric", "status", "category", "updatedAt", "id"],
      fieldHints: {
        title: ["title", "name", "label"],
        metric: ["metric", "value", "count", "total", "score", "rate"],
        status: ["status", "state"],
      },
      intentKeywords: ["테이블", "표", "table", "컬럼", "데이터셋"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["array<object>"], minRows: 1 },
      requiredSlots: [titleSlot(), { slot: "items[].columns", acceptsTypes: ["string", "number", "boolean", "date", "datetime"], acceptsRoles: ["id", "label", "category", "status", "metric", "updatedAt", "time"], minCount: 2, required: true }],
      optionalSlots: [
        { slot: "items[].status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: false },
        { slot: "items[].updatedAt", acceptsTypes: ["date", "datetime", "string"], acceptsRoles: ["updatedAt", "time"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["테이블", "표", "table", "컬럼", "데이터셋"],
        bestFor: ["generic tabular data"],
        badFor: ["mostly booleans", "progress bars", "timeline events"],
        priority: 2,
      },
    },
    surfaceConfig: {
      viewType: "matrix.table",
      titleBinding: "items[].title",
      fieldBindings: ["items[].id", "items[].category", "items[].status", "items[].updatedAt"],
      maxItems: 8,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "matrix.statusMatrix",
    title: "상태 매트릭스",
    description: "boolean 또는 상태 field를 row별 cell로 비교해 보여준다.",
    selectionGuide: "각 row에 여러 boolean/status flag가 있고 ON/OFF, 정상/주의/위험처럼 상태 비교가 핵심일 때 사용한다.",
    schemaSpec: {
      dataShape: "array<object>",
      requiredRoles: ["title", "booleanFlag"],
      optionalRoles: ["status", "category", "updatedAt"],
      minBooleanFields: 2,
      fieldHints: {
        title: ["title", "name", "label"],
        booleanFlag: ["enabled", "active", "isOnline", "isRunning", "blocked", "done", "hasAlarm"],
        status: ["status", "state", "phase"],
      },
      intentKeywords: ["상태", "status", "matrix", "flag", "boolean", "비교"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["array<object>"], minRows: 1, capabilities: { hasBooleans: true, hasStatus: true } },
      requiredSlots: [
        titleSlot(),
        { slot: "items[].statusFlags", acceptsTypes: ["boolean"], acceptsRoles: ["booleanFlag", "status"], minCount: 2, required: true },
      ],
      optionalSlots: [
        { slot: "items[].category", acceptsTypes: ["string"], acceptsRoles: ["category"], required: false },
        { slot: "items[].updatedAt", acceptsTypes: ["date", "datetime", "string"], acceptsRoles: ["updatedAt", "time"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["상태", "status", "matrix", "flag", "boolean", "비교"],
        bestFor: ["boolean/status field comparison"],
        badFor: ["numeric metrics", "single status only", "progress percentages"],
        priority: 8,
      },
    },
    surfaceConfig: {
      viewType: "matrix.statusMatrix",
      titleBinding: "items[].title",
      statusBindings: ["items[].enabled", "items[].active", "items[].isOnline", "items[].isRunning", "items[].hasAlarm"],
      categoryBinding: "items[].category",
      maxItems: 8,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "metric.statCards",
    title: "지표 카드",
    description: "집계 숫자와 변화량을 KPI 카드 묶음으로 보여준다.",
    selectionGuide: "total/count/average/rate/score 같은 summary numeric field가 핵심이고 row별 상세보다 요약이 중요할 때 사용한다.",
    schemaSpec: {
      dataShape: "object",
      requiredRoles: ["metric"],
      optionalRoles: ["title", "delta", "unit", "status"],
      fieldHints: {
        metric: ["total", "count", "average", "avg", "rate", "score", "value"],
        delta: ["delta", "change", "diff", "growth"],
        unit: ["unit", "currency", "uom"],
      },
      intentKeywords: ["지표", "kpi", "metric", "요약", "통계", "summary"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["object", "array<object>"], minRows: 1, maxRows: 4, capabilities: { hasNumericMetrics: true } },
      requiredSlots: [
        { slot: "metrics[].value", acceptsTypes: ["number"], acceptsRoles: ["metric"], minCount: 1, required: true },
      ],
      optionalSlots: [
        { slot: "metrics[].label", acceptsTypes: ["string"], acceptsRoles: ["title", "label", "category"], required: false },
        { slot: "metrics[].delta", acceptsTypes: ["number", "string"], acceptsRoles: ["delta", "metric"], required: false },
        { slot: "metrics[].unit", acceptsTypes: ["string"], acceptsRoles: ["unit"], required: false },
        { slot: "metrics[].status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["지표", "kpi", "metric", "요약", "통계", "summary"],
        bestFor: ["small numeric summary object"],
        badFor: ["row-level progress", "large table"],
        priority: 6,
      },
    },
    surfaceConfig: {
      viewType: "metric.statCards",
      titleBinding: "items[].title",
      metricBindings: ["items[].value"],
      deltaBinding: "items[].delta",
      unitBinding: "items[].unit",
      statusBindings: ["items[].status"],
      maxItems: 4,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "metric.progressList",
    title: "진행률 목록",
    description: "반복 항목의 퍼센트/완료율을 progress bar 목록으로 보여준다.",
    selectionGuide: "각 row에 progress, percent, completionRate, doneRatio 같은 0-1 또는 0-100 진행률 숫자가 있을 때 사용한다.",
    schemaSpec: {
      dataShape: "array<object>",
      requiredRoles: ["title", "progress"],
      optionalRoles: ["content", "description", "status", "updatedAt"],
      fieldHints: {
        title: ["title", "name", "projectName", "taskName", "label"],
        progress: ["progress", "percent", "percentage", "completionRate", "doneRatio", "completionPercent"],
        status: ["status", "state"],
      },
      intentKeywords: ["진행률", "progress", "완료율", "퍼센트", "percent", "완료"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["array<object>"], minRows: 1, capabilities: { hasProgress: true } },
      requiredSlots: [
        titleSlot(),
        { slot: "items[].progress", acceptsTypes: ["number"], acceptsRoles: ["progress", "metric"], required: true },
      ],
      optionalSlots: [
        { slot: "items[].description", acceptsTypes: ["string"], acceptsRoles: ["content", "description"], required: false },
        { slot: "items[].status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: false },
        { slot: "items[].updatedAt", acceptsTypes: ["date", "datetime", "string"], acceptsRoles: ["updatedAt", "time"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["진행률", "progress", "완료율", "퍼센트", "percent", "완료"],
        bestFor: ["row-level progress bars"],
        badFor: ["single KPI summary", "stage workflow without percentage"],
        priority: 9,
      },
    },
    surfaceConfig: {
      viewType: "metric.progressList",
      titleBinding: "items[].title",
      contentBinding: "items[].description",
      progressBinding: "items[].progress",
      statusBindings: ["items[].status"],
      timeBinding: "items[].updatedAt",
      maxItems: 8,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "time.timeline",
    title: "타임라인",
    description: "시작일과 종료일이 있는 작업, 일정, 로드맵 항목을 가로 시간축 위에 보여준다.",
    selectionGuide: "startAt/startDate와 endAt/endDate/dueAt 같은 기간 field가 있고 일정, 로드맵, 기간 비교가 핵심일 때 사용한다.",
    schemaSpec: {
      dataShape: "array<object>",
      requiredRoles: ["title", "startAt"],
      optionalRoles: ["endAt", "dueAt", "duration", "status", "assignee", "lane", "category", "content", "description"],
      fieldHints: {
        title: ["title", "name", "taskName", "milestone", "label"],
        startAt: ["startAt", "startDate", "startedAt", "beginAt", "fromDate"],
        endAt: ["endAt", "endDate", "finishedAt", "dueAt", "deadline", "toDate"],
        lane: ["lane", "track", "team", "group", "category"],
      },
      intentKeywords: ["타임라인", "timeline", "일정", "스케줄", "기간", "로드맵", "gantt"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["array<object>"], minRows: 1, capabilities: { hasTimeField: true, hasTimeRange: true } },
      requiredSlots: [
        { slot: "items[].startAt", acceptsTypes: ["date", "datetime", "string"], acceptsRoles: ["startAt", "time"], required: true },
        titleSlot(),
      ],
      optionalSlots: [
        { slot: "items[].endAt", acceptsTypes: ["date", "datetime", "string"], acceptsRoles: ["endAt", "dueAt", "time"], required: false },
        { slot: "items[].description", acceptsTypes: ["string"], acceptsRoles: ["content", "description"], required: false },
        { slot: "items[].lane", acceptsTypes: ["string"], acceptsRoles: ["lane", "category"], required: false },
        { slot: "items[].assignee", acceptsTypes: ["string"], acceptsRoles: ["assignee", "actor"], required: false },
        { slot: "items[].status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["타임라인", "timeline", "일정", "스케줄", "기간", "로드맵", "gantt"],
        bestFor: ["scheduled work with start and end dates", "roadmap and gantt-like ranges"],
        badFor: ["event logs", "activity history", "time as simple updated metadata"],
        priority: 7,
      },
    },
    surfaceConfig: {
      viewType: "time.timeline",
      titleBinding: "items[].title",
      contentBinding: "items[].description",
      timeBinding: "items[].startAt",
      startBinding: "items[].startAt",
      endBinding: "items[].endAt",
      laneBinding: "items[].lane",
      assigneeBinding: "items[].assignee",
      statusBindings: ["items[].status"],
      maxItems: 8,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "process.queue",
    title: "처리 대기열",
    description: "상태, 우선순위, 담당자, 기한이 있는 처리 대상 목록을 읽기 전용으로 보여준다.",
    selectionGuide: "status/stage/state와 priority/due/assignee/requester 같은 process metadata가 함께 있을 때 사용한다. 버튼이나 승인 액션은 포함하지 않는다.",
    schemaSpec: {
      dataShape: "array<object>",
      requiredRoles: ["title", "status"],
      optionalRoles: ["priority", "assignee", "dueAt", "content", "description", "category"],
      fieldHints: {
        title: ["title", "name", "requestTitle", "taskName", "subject"],
        status: ["status", "state", "stage", "phase"],
        priority: ["priority", "severity", "urgency"],
        assignee: ["assignee", "owner", "manager", "operator"],
        dueAt: ["dueAt", "due_at", "deadline", "targetDate"],
      },
      intentKeywords: ["대기열", "queue", "처리", "작업", "요청", "우선순위", "담당자"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["array<object>"], minRows: 1, capabilities: { hasStatus: true } },
      requiredSlots: [
        titleSlot(),
        { slot: "items[].status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: true },
      ],
      optionalSlots: [
        { slot: "items[].priority", acceptsTypes: ["string", "number"], acceptsRoles: ["priority"], required: false },
        { slot: "items[].assignee", acceptsTypes: ["string"], acceptsRoles: ["assignee", "actor"], required: false },
        { slot: "items[].dueAt", acceptsTypes: ["date", "datetime", "string"], acceptsRoles: ["dueAt", "time"], required: false },
        { slot: "items[].description", acceptsTypes: ["string"], acceptsRoles: ["content", "description"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["대기열", "queue", "처리", "작업", "요청", "우선순위", "담당자"],
        bestFor: ["read-only work queue with status metadata"],
        badFor: ["action approval forms", "pure boolean matrix"],
        priority: 6,
      },
    },
    surfaceConfig: {
      viewType: "process.queue",
      titleBinding: "items[].title",
      contentBinding: "items[].description",
      statusBindings: ["items[].status"],
      priorityBinding: "items[].priority",
      assigneeBinding: "items[].assignee",
      dueAtBinding: "items[].dueAt",
      maxItems: 8,
    },
    status: "registered",
    updatedAt: now,
  },
  {
    componentId: "relation.tree",
    title: "계층 트리",
    description: "중첩 children 또는 id/parentId 관계를 들여쓰기 outline으로 보여준다.",
    selectionGuide: "children/items/nodes 하위 배열이 반복되거나 flat row에 id와 parentId 관계가 있을 때 사용한다.",
    schemaSpec: {
      dataShape: "array<object>",
      requiredRoles: ["title"],
      optionalRoles: ["children", "parentId", "id", "status", "content", "description", "metric"],
      fieldHints: {
        title: ["title", "name", "label"],
        children: ["children", "nodes", "items"],
        parentId: ["parentId", "parent_id", "parent"],
        id: ["id", "nodeId", "key"],
      },
      intentKeywords: ["트리", "tree", "계층", "hierarchy", "구조", "parent", "children"],
    },
    inputSchema: {
      schemaVersion,
      accepts: { shape: ["array<object>", "object"], minRows: 1 },
      requiredSlots: [titleSlot("nodes[].title")],
      optionalSlots: [
        { slot: "nodes[].children", acceptsTypes: ["array"], acceptsRoles: ["children"], required: false },
        { slot: "nodes[].id", acceptsTypes: ["string", "number"], acceptsRoles: ["id"], required: false },
        { slot: "nodes[].parentId", acceptsTypes: ["string", "number"], acceptsRoles: ["parentId"], required: false },
        { slot: "nodes[].description", acceptsTypes: ["string"], acceptsRoles: ["content", "description"], required: false },
        { slot: "nodes[].status", acceptsTypes: ["string", "boolean"], acceptsRoles: ["status", "booleanFlag"], required: false },
      ],
      selectionHints: {
        queryKeywords: ["트리", "tree", "계층", "hierarchy", "구조", "parent", "children"],
        bestFor: ["hierarchical parent-child data"],
        badFor: ["flat list without parent-child relation"],
        priority: 7,
      },
    },
    surfaceConfig: {
      viewType: "relation.tree",
      titleBinding: "items[].title",
      contentBinding: "items[].description",
      childrenBinding: "items[].children",
      parentIdBinding: "items[].parentId",
      statusBindings: ["items[].status"],
      maxItems: 10,
    },
    status: "registered",
    updatedAt: now,
  },
];
